### ISSUE TITLE
High-level issues to deliver and maintain the production system

### ISSUE THREAD

**Issue by joncison** [IFB-ElixirFr/ifbcat#117]
# Important links
- [Entities ](https://docs.google.com/spreadsheets/d/1tMzwkZINvFTj5mUOCBA8MrR8kxjrD6GRfyqH_mT1pi4/edit#gid=43919236)in the model
- [Entity relationships](https://docs.google.com/spreadsheets/d/1tMzwkZINvFTj5mUOCBA8MrR8kxjrD6GRfyqH_mT1pi4/edit#gid=1427280171)
- [Entity properties](https://docs.google.com/spreadsheets/d/1tMzwkZINvFTj5mUOCBA8MrR8kxjrD6GRfyqH_mT1pi4/edit#gid=346104586) (fields of each model)
- [Controlled vocabularies](https://docs.google.com/spreadsheets/d/1tMzwkZINvFTj5mUOCBA8MrR8kxjrD6GRfyqH_mT1pi4/edit#gid=1411184705)

# High level issues
Personal perspective on what the high-level issues are to put the system fully into production (feel free to edit / add others):

- [ ] liaise with experts as required to further refine / develop the model of “Computing facility” [[116](https://github.com/IFB-ElixirFr/ifbcat/issues/116)], and “Service” and “Service submission” (with respect to the ELIXIR-FR SDP process) [[118](https://github.com/IFB-ElixirFr/ifbcat/issues/118)]
- [ ] liaise with FR training experts to refine (then implement) a model of training event metrics [[113](https://github.com/IFB-ElixirFr/ifbcat/issues/113)]
- [ ] implement advanced backend/API features, notably re-use of bio.tools and ORCID APIs: a very lightweight (compared to bio.tools) model of tools and databases is needed, but re-use the bio.tools API) [[39](https://github.com/IFB-ElixirFr/ifbcat/issues/39)]
- [ ] IFB website developers to validate that the API is fit for purpose
- [ ] analyse the existing content and migrate (parts of) it to the new model [[115](https://github.com/IFB-ElixirFr/ifbcat/issues/115), [112](https://github.com/IFB-ElixirFr/ifbcat/issues/112), [117](https://github.com/IFB-ElixirFr/ifbcat/issues/107), [105](https://github.com/IFB-ElixirFr/ifbcat/issues/105), [104](https://github.com/IFB-ElixirFr/ifbcat/issues/104), [103](https://github.com/IFB-ElixirFr/ifbcat/issues/103), [102](https://github.com/IFB-ElixirFr/ifbcat/issues/102), [101](https://github.com/IFB-ElixirFr/ifbcat/issues/101), [109](https://github.com/IFB-ElixirFr/ifbcat/issues/99)]
- [ ] implement basic frontend logic and GUI components as required for registration / curation of content (a combination of Django “Browsable API” and "Admin interface" will suffice in 1st instance) [*multiple open issues, mostly minor*]
- [ ] implementation of unit tests and adoption of test-driven development may be prudent before too long (short term cost for long-term gain) [[97](https://github.com/IFB-ElixirFr/ifbcat/issues/97)]
- [ ] engage with UI design and UX specialists, and implement changes, to ensure GUI has professional look and feel and is highly usable (depends on how far the browsable API / admin interface gets us - going beyond these can be costly!)
- [ ] coordinate end-users to evaluate the system, and implement improvements in light of their feedback (especially of GUI components)
- [ ] implement basic GitHub integration - to export content in JSON format into a repo
- [ ] implement advanced Git integration to ensure content can be maintained seamlessly in e.g. GitHub - requires formalised JSON schema, content validation mechanism etc.
- [ ] implement “pull” mechanism to harvest metadata from local webpages (if required - may be desirable in the longer term for some entities) 
- [ ] improve and extend the entire system over time as new requirements emerge
- [ ] foster the community of content providers to provide or maintain their own content
- [ ] routine maintenance of the system and user-support (housekeeping)
